version: "3"
services:
  db: # DB container
    image: rethinkdb:2.3.5 # Get latest rethinkdb release
    ports: # Expose rethinkdb admin tool and tcp
      - "8080:8080"
      - "28015:28015"
  api: # API container
    build: music-api/. # Path to the Dockerfile
    command: npm start # The desired command to run at docker-compose up
    links: # Create a link between this container and our db container
      - db 
    depends_on:
      - db
    volumes: # Link our volumes path_to_host_files:path_to_container
      - ./music-api:/usr/src/app
    ports: # Expose the API listening port
      - "3000:3000"
